In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7921, 426, 2861, 227],
 [7921, 426, 2861, 9314],
 [7921, 3313, 2861, 9737],
 [7037, 5046, 1469, 9003, 3075],
 [7037, 5046, 1469, 9003, 299],
 [4731, 7921, 5668, 2861, 7729],
 [6634, 1386, 6498, 9003]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7921  426 2861  227]
 [   0    0    0    0 7921  426 2861 9314]
 [   0    0    0    0 7921 3313 2861 9737]
 [   0    0    0 7037 5046 1469 9003 3075]
 [   0    0    0 7037 5046 1469 9003  299]
 [   0    0    0 4731 7921 5668 2861 7729]
 [   0    0    0    0 6634 1386 6498 9003]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 64ms/step


array([[[-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [ 0.00292282,  0.04393566, -0.03843201,  0.02647645,
         -0.00878993, -0.03272483,  0.01989673, -0.00265769,
          0.01213696, -0.04142426],
        [-0.04131039, -0.02984929, -0.03953128, -0.02418535,
         -0.00423713,  0.00195634,  0.024205  ,  0.00320877,
          0.03915927,  0.03262098],
        [ 0.01963672, -0.04150517, -0.01727641, -0.0

In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 24ms/step


array([[[-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [-0.00896299, -0.01561346,  0.03088316, -0.01937513,
          0.04721401, -0.03835547, -0.00996549, -0.02878481,
          0.02420504,  0.01815503],
        [ 0.00292282,  0.04393566, -0.03843201,  0.02647645,
         -0.00878993, -0.03272483,  0.01989673, -0.00265769,
          0.01213696, -0.04142426],
        [-0.04131039, -0.02984929, -0.03953128, -0.02418535,
         -0.00423713,  0.00195634,  0.024205  ,  0.00320877,
          0.03915927,  0.03262098],
        [ 0.01963672, -0.04150517, -0.01727641, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7921,  426, 2861,  227])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 43ms/step


array([[-0.00896299, -0.01561346,  0.03088316, -0.01937513,  0.04721401,
        -0.03835547, -0.00996549, -0.02878481,  0.02420504,  0.01815503],
       [-0.00896299, -0.01561346,  0.03088316, -0.01937513,  0.04721401,
        -0.03835547, -0.00996549, -0.02878481,  0.02420504,  0.01815503],
       [-0.00896299, -0.01561346,  0.03088316, -0.01937513,  0.04721401,
        -0.03835547, -0.00996549, -0.02878481,  0.02420504,  0.01815503],
       [-0.00896299, -0.01561346,  0.03088316, -0.01937513,  0.04721401,
        -0.03835547, -0.00996549, -0.02878481,  0.02420504,  0.01815503],
       [ 0.00292282,  0.04393566, -0.03843201,  0.02647645, -0.00878993,
        -0.03272483,  0.01989673, -0.00265769,  0.01213696, -0.04142426],
       [-0.04131039, -0.02984929, -0.03953128, -0.02418535, -0.00423713,
         0.00195634,  0.024205  ,  0.00320877,  0.03915927,  0.03262098],
       [ 0.01963672, -0.04150517, -0.01727641, -0.02569007, -0.02927462,
         0.0020954 ,  0.00416392,  0.00659814